package com.k.sekiro.musico.playmusic.presenation.player.service

const val CUSTOM_COMMAND_START_SLEEP_TIMER_ACTION = "START_SLEEP_TIMER"
const val CUSTOM_COMMAND_START_SLEEP_TIMER_END_OF_TRACK_ACTION = "START_SLEEP_TIMER_END_OF_TRACK"
const val CUSTOM_COMMAND_CANCEL_SLEEP_TIMER_ACTION = "CANCEL_SLEEP_TIMER"
const val SLEEP_TIMER_DURATION_ARG = "sleepTimerDurationMillis"

const val SLEEP_TIMER_MODE_OFF = "OFF"
const val SLEEP_TIMER_MODE_DURATION = "DURATION"
const val SLEEP_TIMER_MODE_END_OF_TRACK = "END_OF_TRACK"
